### ISSUE TITLE
rmf_demos installation - colcon build error (stderr: test_maps...)

### ISSUE THREAD

**Issue by albertleng** [osrf/rmf_demos#157]
To install and run rmf_demos, I followed steps in [rmf_demos_installation](https://github.com/osrf/rmf_demos/blob/master/docs/installation.md).

Everything went as expected until [Compiling-Ubuntu20.04](https://github.com/osrf/rmf_demos/blob/master/docs/installation.md#ubuntu-2004). I got the following error:
```
`--- stderr: test_maps
Traceback (most recent call last):
  File "/home/albert/rmf_demos_ws/install/building_map_tools/lib/building_map_tools/building_map_generator", line 11, in <module>
    load_entry_point('building-map-tools==0.0.0', 'console_scripts', 'building_map_generator')()
  File "/home/albert/rmf_demos_ws/install/building_map_tools/lib/python3.8/site-packages/building_map_generator/building_map_generator.py", line 16, in main
    g.generate_gazebo_sdf(
  File "/home/albert/rmf_demos_ws/install/building_map_tools/lib/python3.8/site-packages/building_map/generator.py", line 59, in generate_gazebo_sdf
    self.generate_sdf(
  File "/home/albert/rmf_demos_ws/install/building_map_tools/lib/python3.8/site-packages/building_map/generator.py", line 44, in generate_sdf
    sdf = building.generate_sdf_world(options)
  File "/home/albert/rmf_demos_ws/install/building_map_tools/lib/python3.8/site-packages/building_map/building.py", line 207, in generate_sdf_world
    level.generate_doors(world, options)
  File "/home/albert/rmf_demos_ws/install/building_map_tools/lib/python3.8/site-packages/building_map/level.py", line 174, in generate_doors
    self.generate_door(door_edge, world_ele, options)
  File "/home/albert/rmf_demos_ws/install/building_map_tools/lib/python3.8/site-packages/building_map/level.py", line 189, in generate_door
    door = DoubleSwingDoor(door_edge, self.elevation)
  File "/home/albert/rmf_demos_ws/install/building_map_tools/lib/python3.8/site-packages/building_map/doors/double_swing_door.py", line 7, in __init__
    super().__init__(door_edge, level_elevation)
  File "/home/albert/rmf_demos_ws/install/building_map_tools/lib/python3.8/site-packages/building_map/doors/door.py", line 9, in __init__
    self.plugin = door_edge.params['plugin'].value
KeyError: 'plugin'
make[2]: *** [CMakeFiles/generate_door_madness.dir/build.make:61: maps/door_madness/door_madness.world] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/generate_door_madness.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< test_maps [0.84s, exited with code 2]

Summary: 35 packages finished [20.7s]
  1 package failed: test_maps
  1 package had stderr output: test_maps`


```
Attached is the build log. Let me know if you need any additional info. Thanks.
[rmf_demos_github_issues_tracker.txt](https://github.com/osrf/rmf_demos/files/5464165/rmf_demos_github_issues_tracker.txt)

**Comment by Yadunund** [comment]
Hello!

We recently merged a [PR](https://github.com/osrf/traffic_editor/pull/255) that adds the option to have doors and lifts to be generated with/without plugins. But the change is not backwards compatible with traffic editor maps in the old format. We are currently addressing this issue.

In the meanwhile could you add `--packages-ignore test_maps` to your colcon command? That should ignore building the `test_maps` package that is currently failing.

**Comment by albertleng** [comment]
Thank you. 
With `colcon build --packages_ignore test_maps --cmake-args --DCMAKE_BUILD_TYPE=RELEASE` , I could build with no error. Let me fiddle with the [demos](https://github.com/osrf/rmf_demos).
