### ISSUE TITLE
Error launching demos

### ISSUE THREAD

**Issue by kurshakuz** [osrf/rmf_demos#49]
I have followed the installation instructions and tried to run
` $ ros2 launch -d demos office.launch.xml`
but this what I get
```
[INFO] [launch]: All log files can be found below /home/shyngys/.ros/log/2020-03-29-19-13-34-445338-shyngys-HP-ENVY-15-Notebook-PC-13832
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): The launch file may have a syntax error, or its format is unknown
```
Log files have the same information.
Running the detailed output shows:
```
$ ros2 launch -d demos office.launch.xml
[DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.IncludeLaunchDescription'
[DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.IncludeLaunchDescription'
[INFO] [launch]: All log files can be found below /home/shyngys/.ros/log/2020-03-29-19-14-05-631021-shyngys-HP-ENVY-15-Notebook-PC-13851
[INFO] [launch]: Default logging verbosity is set to DEBUG
[DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7f310e7a8390>'
[DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7f310e7a8390>' ✓ '<launch.event_handlers.on_include_launch_description.OnIncludeLaunchDescription object at 0x7f3104493978>'
[DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7f31005b6048>'
[DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7f31005b6048>' ✓ '<launch.event_handlers.on_include_launch_description.OnIncludeLaunchDescription object at 0x7f3104493978>'
[DEBUG] [launch]: Traceback (most recent call last):
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py", line 385, in run_async
    await process_one_event_task
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 126, in send
    return self.gen.send(value)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py", line 295, in _process_one_event
    await self.__process_event(next_event)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py", line 315, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/actions/include_launch_description.py", line 125, in execute
    launch_description = self.__launch_description_source.get_launch_description(context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_description_source.py", line 84, in get_launch_description
    self._get_launch_description(self.__expanded_location)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_description_sources/any_launch_description_source.py", line 53, in _get_launch_description
    return get_launch_description_from_any_launch_file(location)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 56, in get_launch_description_from_any_launch_file
    raise InvalidLaunchFileError(extension, likely_errors=exceptions)
launch.invalid_launch_file_error.InvalidLaunchFileError: The launch file may have a syntax error, or its format is unknown

[ERROR] [launch]: Caught exception in launch (see debug for traceback): The launch file may have a syntax error, or its format is unknown
[DEBUG] [launch.launch_context]: emitting event: 'launch.events.Shutdown'
[DEBUG] [launch]: processing event: '<launch.events.shutdown.Shutdown object at 0x7f30fc455f60>'
[DEBUG] [launch]: processing event: '<launch.events.shutdown.Shutdown object at 0x7f30fc455f60>' ✓ '<launch.event_handlers.on_shutdown.OnShutdown object at 0x7f30fc4559b0>'
[DEBUG] [launch]: processing event: '<launch.events.shutdown.Shutdown object at 0x7f30fc455f60>' ✓ '<launch.event_handlers.on_shutdown.OnShutdown object at 0x7f310ca41ef0>'
Executing <Task finished coro=<LaunchService._process_one_event() done, defined at /opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py:293> result=None created at /opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py:363> took 1.000 seconds
```
I have looked at the launch file and everything seems ok. Have anyone met this issue?
(I have additionally, uninstalled the apt version of gazebo and installed it using rosdep, but result is the same)

**Comment by aaronchongth** [comment]
This might be due to a missing dependency for `launch-xml`, could you try `sudo apt install ros-eloquent-launch*`, and try launching the demo again?

**Comment by kurshakuz** [comment]
Hi @aaronchongth, that actually helped! May it is better to be included in the "Setup" part as well? 

Additionally, I have met  an issue during launching an Office World, but I will create new one and mark this one as solved.

Thanks!

**Comment by aaronchongth** [comment]
we are hoping to have it added to the main full `ros-eloquent` binary, but it seems it might have not happened yet, I'll patch in the instructions in the meantime
